# Generated by Django 4.0.8 on 2024-05-13 23:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField(max_length=400)),
                ('image', models.ImageField(blank=True, upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=300, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=400)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ecommerce.image', verbose_name='Categoría asociada')),
            ],
        ),
    ]
